steps:
  - name: 'gcr.io/cloud-builders/docker'
    id: Build
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/redis-commander:1.0.3', '-t', 'gcr.io/$PROJECT_ID/redis-commander:latest', '.']

images:
  - 'gcr.io/$PROJECT_ID/redis-commander:latest'
  - 'gcr.io/$PROJECT_ID/redis-commander:1.0.3'
