name: Stag Deploy
run-name: redis-commander-${{ github.ref_name }}

on:
  push:
    branches:
      - INFRA-4132

  workflow_dispatch:

jobs:
  # set_env:
  #   runs-on:
  #     - self-hosted
  #     - "flo-stag"
  #   outputs:
  # ACCOUNT:
  #     APP_ENV: stag
  #     APP_NAME: redis-commander
  #     CLUSTER: stag
  #     LOG_LEVEL: trace
  #     DOMAIN: redis-commander.stag-aws.flokubernetes.com
  #   steps: [{ run: "exit 0" }] # noop step to satisfy job requirements

  build:
    # needs: [set_env]
    uses: flocasts/github-actions/.github/workflows/shared-build-container.yaml@main
    with:
      app-env: stag
      app-name: redis-commander
      build-role: github-actions-deploy-role
      build-args: |
        --progress=plain
      region: us-west-2
